// Code generated by protoc-gen-go. DO NOT EDIT.
// source: whoami.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_OK                  Status = 0
	Status_CANCELLED           Status = 1
	Status_UNKNOWN             Status = 2
	Status_INVALID_ARGUMENT    Status = 3
	Status_DEADLINE_EXCEEDED   Status = 4
	Status_NOT_FOUND           Status = 5
	Status_ALREADY_EXISTS      Status = 6
	Status_PERMISSION_DENIED   Status = 7
	Status_RESOURCE_EXHAUSTED  Status = 8
	Status_FAILED_PRECONDITION Status = 9
	Status_ABORTED             Status = 10
	Status_OUT_OF_RANGE        Status = 11
	Status_UNIMPLEMENTED       Status = 12
	Status_INTERNAL            Status = 13
	Status_UNAVAILABLE         Status = 14
	Status_DATA_LOSS           Status = 15
	Status_UNAUTHENTICATED     Status = 16
)

var Status_name = map[int32]string{
	0:  "OK",
	1:  "CANCELLED",
	2:  "UNKNOWN",
	3:  "INVALID_ARGUMENT",
	4:  "DEADLINE_EXCEEDED",
	5:  "NOT_FOUND",
	6:  "ALREADY_EXISTS",
	7:  "PERMISSION_DENIED",
	8:  "RESOURCE_EXHAUSTED",
	9:  "FAILED_PRECONDITION",
	10: "ABORTED",
	11: "OUT_OF_RANGE",
	12: "UNIMPLEMENTED",
	13: "INTERNAL",
	14: "UNAVAILABLE",
	15: "DATA_LOSS",
	16: "UNAUTHENTICATED",
}

var Status_value = map[string]int32{
	"OK":                  0,
	"CANCELLED":           1,
	"UNKNOWN":             2,
	"INVALID_ARGUMENT":    3,
	"DEADLINE_EXCEEDED":   4,
	"NOT_FOUND":           5,
	"ALREADY_EXISTS":      6,
	"PERMISSION_DENIED":   7,
	"RESOURCE_EXHAUSTED":  8,
	"FAILED_PRECONDITION": 9,
	"ABORTED":             10,
	"OUT_OF_RANGE":        11,
	"UNIMPLEMENTED":       12,
	"INTERNAL":            13,
	"UNAVAILABLE":         14,
	"DATA_LOSS":           15,
	"UNAUTHENTICATED":     16,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f60ba8fc50e3624, []int{0}
}

type GetDataRequest struct {
	Size                 int64    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataRequest) Reset()         { *m = GetDataRequest{} }
func (m *GetDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetDataRequest) ProtoMessage()    {}
func (*GetDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f60ba8fc50e3624, []int{0}
}

func (m *GetDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataRequest.Unmarshal(m, b)
}
func (m *GetDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataRequest.Marshal(b, m, deterministic)
}
func (m *GetDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataRequest.Merge(m, src)
}
func (m *GetDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetDataRequest.Size(m)
}
func (m *GetDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataRequest proto.InternalMessageInfo

func (m *GetDataRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type GetDataResponse struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataResponse) Reset()         { *m = GetDataResponse{} }
func (m *GetDataResponse) String() string { return proto.CompactTextString(m) }
func (*GetDataResponse) ProtoMessage()    {}
func (*GetDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f60ba8fc50e3624, []int{1}
}

func (m *GetDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataResponse.Unmarshal(m, b)
}
func (m *GetDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataResponse.Marshal(b, m, deterministic)
}
func (m *GetDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataResponse.Merge(m, src)
}
func (m *GetDataResponse) XXX_Size() int {
	return xxx_messageInfo_GetDataResponse.Size(m)
}
func (m *GetDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataResponse proto.InternalMessageInfo

func (m *GetDataResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type BenchRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BenchRequest) Reset()         { *m = BenchRequest{} }
func (m *BenchRequest) String() string { return proto.CompactTextString(m) }
func (*BenchRequest) ProtoMessage()    {}
func (*BenchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f60ba8fc50e3624, []int{2}
}

func (m *BenchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BenchRequest.Unmarshal(m, b)
}
func (m *BenchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BenchRequest.Marshal(b, m, deterministic)
}
func (m *BenchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BenchRequest.Merge(m, src)
}
func (m *BenchRequest) XXX_Size() int {
	return xxx_messageInfo_BenchRequest.Size(m)
}
func (m *BenchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BenchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BenchRequest proto.InternalMessageInfo

type BenchResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BenchResponse) Reset()         { *m = BenchResponse{} }
func (m *BenchResponse) String() string { return proto.CompactTextString(m) }
func (*BenchResponse) ProtoMessage()    {}
func (*BenchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f60ba8fc50e3624, []int{3}
}

func (m *BenchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BenchResponse.Unmarshal(m, b)
}
func (m *BenchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BenchResponse.Marshal(b, m, deterministic)
}
func (m *BenchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BenchResponse.Merge(m, src)
}
func (m *BenchResponse) XXX_Size() int {
	return xxx_messageInfo_BenchResponse.Size(m)
}
func (m *BenchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BenchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BenchResponse proto.InternalMessageInfo

func (m *BenchResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type GetWhoamiRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWhoamiRequest) Reset()         { *m = GetWhoamiRequest{} }
func (m *GetWhoamiRequest) String() string { return proto.CompactTextString(m) }
func (*GetWhoamiRequest) ProtoMessage()    {}
func (*GetWhoamiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f60ba8fc50e3624, []int{4}
}

func (m *GetWhoamiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWhoamiRequest.Unmarshal(m, b)
}
func (m *GetWhoamiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWhoamiRequest.Marshal(b, m, deterministic)
}
func (m *GetWhoamiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWhoamiRequest.Merge(m, src)
}
func (m *GetWhoamiRequest) XXX_Size() int {
	return xxx_messageInfo_GetWhoamiRequest.Size(m)
}
func (m *GetWhoamiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWhoamiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWhoamiRequest proto.InternalMessageInfo

type GetWhoamiResponse struct {
	Hostname             string            `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip                   []string          `protobuf:"bytes,2,rep,name=ip,proto3" json:"ip,omitempty"`
	Header               map[string]string `protobuf:"bytes,3,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Url                  string            `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Host                 string            `protobuf:"bytes,5,opt,name=host,proto3" json:"host,omitempty"`
	Rpc                  string            `protobuf:"bytes,6,opt,name=rpc,proto3" json:"rpc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetWhoamiResponse) Reset()         { *m = GetWhoamiResponse{} }
func (m *GetWhoamiResponse) String() string { return proto.CompactTextString(m) }
func (*GetWhoamiResponse) ProtoMessage()    {}
func (*GetWhoamiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f60ba8fc50e3624, []int{5}
}

func (m *GetWhoamiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWhoamiResponse.Unmarshal(m, b)
}
func (m *GetWhoamiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWhoamiResponse.Marshal(b, m, deterministic)
}
func (m *GetWhoamiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWhoamiResponse.Merge(m, src)
}
func (m *GetWhoamiResponse) XXX_Size() int {
	return xxx_messageInfo_GetWhoamiResponse.Size(m)
}
func (m *GetWhoamiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWhoamiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWhoamiResponse proto.InternalMessageInfo

func (m *GetWhoamiResponse) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *GetWhoamiResponse) GetIp() []string {
	if m != nil {
		return m.Ip
	}
	return nil
}

func (m *GetWhoamiResponse) GetHeader() map[string]string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetWhoamiResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *GetWhoamiResponse) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *GetWhoamiResponse) GetRpc() string {
	if m != nil {
		return m.Rpc
	}
	return ""
}

type GetHealthRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHealthRequest) Reset()         { *m = GetHealthRequest{} }
func (m *GetHealthRequest) String() string { return proto.CompactTextString(m) }
func (*GetHealthRequest) ProtoMessage()    {}
func (*GetHealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f60ba8fc50e3624, []int{6}
}

func (m *GetHealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHealthRequest.Unmarshal(m, b)
}
func (m *GetHealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHealthRequest.Marshal(b, m, deterministic)
}
func (m *GetHealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHealthRequest.Merge(m, src)
}
func (m *GetHealthRequest) XXX_Size() int {
	return xxx_messageInfo_GetHealthRequest.Size(m)
}
func (m *GetHealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHealthRequest proto.InternalMessageInfo

type GetHealthResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHealthResponse) Reset()         { *m = GetHealthResponse{} }
func (m *GetHealthResponse) String() string { return proto.CompactTextString(m) }
func (*GetHealthResponse) ProtoMessage()    {}
func (*GetHealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f60ba8fc50e3624, []int{7}
}

func (m *GetHealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHealthResponse.Unmarshal(m, b)
}
func (m *GetHealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHealthResponse.Marshal(b, m, deterministic)
}
func (m *GetHealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHealthResponse.Merge(m, src)
}
func (m *GetHealthResponse) XXX_Size() int {
	return xxx_messageInfo_GetHealthResponse.Size(m)
}
func (m *GetHealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHealthResponse proto.InternalMessageInfo

func (m *GetHealthResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type SetHealthRequest struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=com.wdullaer.whoami.v1.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetHealthRequest) Reset()         { *m = SetHealthRequest{} }
func (m *SetHealthRequest) String() string { return proto.CompactTextString(m) }
func (*SetHealthRequest) ProtoMessage()    {}
func (*SetHealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f60ba8fc50e3624, []int{8}
}

func (m *SetHealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetHealthRequest.Unmarshal(m, b)
}
func (m *SetHealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetHealthRequest.Marshal(b, m, deterministic)
}
func (m *SetHealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetHealthRequest.Merge(m, src)
}
func (m *SetHealthRequest) XXX_Size() int {
	return xxx_messageInfo_SetHealthRequest.Size(m)
}
func (m *SetHealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetHealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetHealthRequest proto.InternalMessageInfo

func (m *SetHealthRequest) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

type SetHealthResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetHealthResponse) Reset()         { *m = SetHealthResponse{} }
func (m *SetHealthResponse) String() string { return proto.CompactTextString(m) }
func (*SetHealthResponse) ProtoMessage()    {}
func (*SetHealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f60ba8fc50e3624, []int{9}
}

func (m *SetHealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetHealthResponse.Unmarshal(m, b)
}
func (m *SetHealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetHealthResponse.Marshal(b, m, deterministic)
}
func (m *SetHealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetHealthResponse.Merge(m, src)
}
func (m *SetHealthResponse) XXX_Size() int {
	return xxx_messageInfo_SetHealthResponse.Size(m)
}
func (m *SetHealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetHealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetHealthResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("com.wdullaer.whoami.v1.Status", Status_name, Status_value)
	proto.RegisterType((*GetDataRequest)(nil), "com.wdullaer.whoami.v1.GetDataRequest")
	proto.RegisterType((*GetDataResponse)(nil), "com.wdullaer.whoami.v1.GetDataResponse")
	proto.RegisterType((*BenchRequest)(nil), "com.wdullaer.whoami.v1.BenchRequest")
	proto.RegisterType((*BenchResponse)(nil), "com.wdullaer.whoami.v1.BenchResponse")
	proto.RegisterType((*GetWhoamiRequest)(nil), "com.wdullaer.whoami.v1.GetWhoamiRequest")
	proto.RegisterType((*GetWhoamiResponse)(nil), "com.wdullaer.whoami.v1.GetWhoamiResponse")
	proto.RegisterMapType((map[string]string)(nil), "com.wdullaer.whoami.v1.GetWhoamiResponse.HeaderEntry")
	proto.RegisterType((*GetHealthRequest)(nil), "com.wdullaer.whoami.v1.GetHealthRequest")
	proto.RegisterType((*GetHealthResponse)(nil), "com.wdullaer.whoami.v1.GetHealthResponse")
	proto.RegisterType((*SetHealthRequest)(nil), "com.wdullaer.whoami.v1.SetHealthRequest")
	proto.RegisterType((*SetHealthResponse)(nil), "com.wdullaer.whoami.v1.SetHealthResponse")
}

func init() { proto.RegisterFile("whoami.proto", fileDescriptor_3f60ba8fc50e3624) }

var fileDescriptor_3f60ba8fc50e3624 = []byte{
	// 703 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x6e, 0xf2, 0x46,
	0x10, 0x2d, 0x06, 0x0c, 0x0c, 0x7f, 0xcb, 0x26, 0x4d, 0x2d, 0x2e, 0xaa, 0x88, 0xa6, 0x0d, 0x6d,
	0x25, 0xa4, 0xa6, 0x6a, 0xd5, 0xf6, 0x6e, 0x61, 0x37, 0xe0, 0xc6, 0xac, 0xa3, 0xb5, 0x9d, 0xa4,
	0xb9, 0x71, 0x1c, 0xb2, 0x12, 0x28, 0x04, 0x53, 0xdb, 0x24, 0x4a, 0xef, 0xfa, 0x58, 0x7d, 0xa2,
	0xbe, 0x46, 0x65, 0xb3, 0x41, 0x34, 0xf9, 0xf2, 0x73, 0xb7, 0x33, 0x3e, 0x73, 0xce, 0xe8, 0x68,
	0x8e, 0xa1, 0xf6, 0x30, 0x0d, 0x83, 0xbb, 0x59, 0x6f, 0x19, 0x85, 0x49, 0x88, 0xf7, 0x26, 0xe1,
	0x5d, 0xef, 0xe1, 0x66, 0x35, 0x9f, 0x07, 0x32, 0xea, 0xa9, 0x4f, 0xf7, 0x3f, 0x74, 0x0e, 0xa0,
	0x31, 0x94, 0x09, 0x0d, 0x92, 0x40, 0xc8, 0x3f, 0x57, 0x32, 0x4e, 0x30, 0x86, 0x42, 0x3c, 0xfb,
	0x4b, 0x1a, 0xb9, 0xfd, 0x5c, 0x37, 0x2f, 0xb2, 0x77, 0xe7, 0x7b, 0x68, 0x6e, 0x50, 0xf1, 0x32,
	0x5c, 0xc4, 0x12, 0x1b, 0x50, 0x9a, 0x84, 0x8b, 0x44, 0x2e, 0x92, 0x0c, 0x59, 0x11, 0x4f, 0x65,
	0xa7, 0x01, 0xb5, 0xbe, 0x5c, 0x4c, 0xa6, 0x8a, 0xb0, 0x73, 0x08, 0x75, 0x55, 0xab, 0xd1, 0x3d,
	0xd0, 0x23, 0x19, 0xaf, 0xe6, 0xeb, 0xc9, 0xa2, 0x50, 0x55, 0x07, 0x03, 0x1a, 0xca, 0xe4, 0x3c,
	0xdb, 0xed, 0x69, 0xf8, 0x6f, 0x0d, 0x5a, 0x5b, 0x4d, 0xc5, 0xd0, 0x86, 0xf2, 0x34, 0x8c, 0x93,
	0x45, 0x70, 0x27, 0x95, 0xfa, 0xa6, 0xc6, 0x0d, 0xd0, 0x66, 0x4b, 0x43, 0xdb, 0xcf, 0x77, 0x2b,
	0x42, 0x9b, 0x2d, 0xf1, 0x18, 0xf4, 0xa9, 0x0c, 0x6e, 0x64, 0x64, 0xe4, 0xf7, 0xf3, 0xdd, 0xea,
	0xd1, 0x4f, 0xbd, 0x4f, 0x5b, 0xd1, 0x7b, 0x21, 0xd3, 0x1b, 0x65, 0x73, 0x6c, 0x91, 0x44, 0x8f,
	0x42, 0x91, 0x60, 0x04, 0xf9, 0x55, 0x34, 0x37, 0x0a, 0x99, 0x6a, 0xfa, 0x4c, 0x0d, 0x4b, 0xc5,
	0x8d, 0x62, 0xd6, 0xca, 0xde, 0x29, 0x2a, 0x5a, 0x4e, 0x0c, 0x7d, 0x8d, 0x8a, 0x96, 0x93, 0xf6,
	0xaf, 0x50, 0xdd, 0xa2, 0x4b, 0x01, 0xb7, 0xf2, 0x51, 0x2d, 0x9f, 0x3e, 0xf1, 0x2e, 0x14, 0xef,
	0x83, 0xf9, 0x4a, 0x1a, 0x5a, 0xd6, 0x5b, 0x17, 0xbf, 0x69, 0xbf, 0xe4, 0x94, 0x2f, 0x23, 0x19,
	0xcc, 0x93, 0x8d, 0xa9, 0x5f, 0x65, 0xb6, 0x3c, 0xf5, 0x94, 0x2d, 0x0d, 0xd0, 0xc2, 0xdb, 0x8c,
	0xb3, 0x2c, 0xb4, 0xf0, 0xb6, 0xf3, 0x3b, 0x20, 0xe7, 0xd9, 0x20, 0xfe, 0x19, 0xf4, 0x38, 0x09,
	0x92, 0x55, 0x9c, 0xe1, 0x1a, 0x47, 0x5f, 0xbe, 0x66, 0x87, 0x93, 0xa1, 0x84, 0x42, 0x77, 0x76,
	0xa0, 0xe5, 0x3c, 0x17, 0xfc, 0xee, 0x1f, 0x0d, 0xf4, 0x35, 0x0e, 0xeb, 0xa0, 0xd9, 0x27, 0xe8,
	0x33, 0x5c, 0x87, 0xca, 0x80, 0xf0, 0x01, 0xb3, 0x2c, 0x46, 0x51, 0x0e, 0x57, 0xa1, 0xe4, 0xf1,
	0x13, 0x6e, 0x9f, 0x73, 0xa4, 0xe1, 0x5d, 0x40, 0x26, 0x3f, 0x23, 0x96, 0x49, 0x7d, 0x22, 0x86,
	0xde, 0x98, 0x71, 0x17, 0xe5, 0xf1, 0xe7, 0xd0, 0xa2, 0x8c, 0x50, 0xcb, 0xe4, 0xcc, 0x67, 0x17,
	0x03, 0xc6, 0x28, 0xa3, 0xa8, 0x90, 0x12, 0x71, 0xdb, 0xf5, 0x8f, 0x6d, 0x8f, 0x53, 0x54, 0xc4,
	0x18, 0x1a, 0xc4, 0x12, 0x8c, 0xd0, 0x3f, 0x7c, 0x76, 0x61, 0x3a, 0xae, 0x83, 0xf4, 0x74, 0xf2,
	0x94, 0x89, 0xb1, 0xe9, 0x38, 0xa6, 0xcd, 0x7d, 0xca, 0xb8, 0xc9, 0x28, 0x2a, 0xe1, 0x3d, 0xc0,
	0x82, 0x39, 0xb6, 0x27, 0x06, 0x29, 0xe1, 0x88, 0x78, 0x8e, 0xcb, 0x28, 0x2a, 0xe3, 0x2f, 0x60,
	0xe7, 0x98, 0x98, 0x16, 0xa3, 0xfe, 0xa9, 0x60, 0x03, 0x9b, 0x53, 0xd3, 0x35, 0x6d, 0x8e, 0x2a,
	0xe9, 0x92, 0xa4, 0x6f, 0x8b, 0x14, 0x05, 0x18, 0x41, 0xcd, 0xf6, 0x5c, 0xdf, 0x3e, 0xf6, 0x05,
	0xe1, 0x43, 0x86, 0xaa, 0xb8, 0x05, 0x75, 0x8f, 0x9b, 0xe3, 0x53, 0x8b, 0xa5, 0x1b, 0x33, 0x8a,
	0x6a, 0xb8, 0x06, 0x65, 0x93, 0xbb, 0x4c, 0x70, 0x62, 0xa1, 0x3a, 0x6e, 0x42, 0xd5, 0xe3, 0xe4,
	0x8c, 0x98, 0x16, 0xe9, 0x5b, 0x0c, 0x35, 0xd2, 0xdd, 0x29, 0x71, 0x89, 0x6f, 0xd9, 0x8e, 0x83,
	0x9a, 0x78, 0x07, 0x9a, 0x1e, 0x27, 0x9e, 0x3b, 0x62, 0xdc, 0x35, 0x07, 0x24, 0xa5, 0x40, 0x47,
	0xff, 0xe6, 0xa1, 0xbe, 0xbe, 0x37, 0x47, 0x46, 0xf7, 0xb3, 0x89, 0xc4, 0x97, 0x50, 0x52, 0x29,
	0xc3, 0xdf, 0xbc, 0x71, 0xa4, 0x5b, 0x61, 0x6d, 0x1f, 0xbe, 0x8b, 0x53, 0xa7, 0xe1, 0x42, 0x31,
	0x0b, 0x21, 0x3e, 0x78, 0x6d, 0x62, 0x3b, 0xb3, 0xed, 0xaf, 0xdf, 0x41, 0x29, 0xd6, 0x2b, 0xa8,
	0x6c, 0x52, 0x83, 0xbb, 0x1f, 0x08, 0xd6, 0x9a, 0xfd, 0xdb, 0x0f, 0x47, 0x50, 0x29, 0xac, 0xcf,
	0xee, 0x4d, 0x85, 0xff, 0x5d, 0xf9, 0x9b, 0x0a, 0xcf, 0x42, 0x73, 0x05, 0x15, 0xe7, 0x7d, 0x05,
	0xe7, 0xc3, 0x0a, 0x2f, 0x52, 0xd2, 0x2f, 0x5c, 0x6a, 0xcb, 0xeb, 0x6b, 0x3d, 0xfb, 0x11, 0xff,
	0xf8, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcb, 0xdb, 0x51, 0x0f, 0x98, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WhoamiServiceClient is the client API for WhoamiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WhoamiServiceClient interface {
	GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error)
	Bench(ctx context.Context, in *BenchRequest, opts ...grpc.CallOption) (*BenchResponse, error)
	GetWhoami(ctx context.Context, in *GetWhoamiRequest, opts ...grpc.CallOption) (*GetWhoamiResponse, error)
	GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error)
	SetHealth(ctx context.Context, in *SetHealthRequest, opts ...grpc.CallOption) (*SetHealthResponse, error)
}

type whoamiServiceClient struct {
	cc *grpc.ClientConn
}

func NewWhoamiServiceClient(cc *grpc.ClientConn) WhoamiServiceClient {
	return &whoamiServiceClient{cc}
}

func (c *whoamiServiceClient) GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error) {
	out := new(GetDataResponse)
	err := c.cc.Invoke(ctx, "/com.wdullaer.whoami.v1.WhoamiService/GetData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whoamiServiceClient) Bench(ctx context.Context, in *BenchRequest, opts ...grpc.CallOption) (*BenchResponse, error) {
	out := new(BenchResponse)
	err := c.cc.Invoke(ctx, "/com.wdullaer.whoami.v1.WhoamiService/Bench", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whoamiServiceClient) GetWhoami(ctx context.Context, in *GetWhoamiRequest, opts ...grpc.CallOption) (*GetWhoamiResponse, error) {
	out := new(GetWhoamiResponse)
	err := c.cc.Invoke(ctx, "/com.wdullaer.whoami.v1.WhoamiService/GetWhoami", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whoamiServiceClient) GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error) {
	out := new(GetHealthResponse)
	err := c.cc.Invoke(ctx, "/com.wdullaer.whoami.v1.WhoamiService/GetHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whoamiServiceClient) SetHealth(ctx context.Context, in *SetHealthRequest, opts ...grpc.CallOption) (*SetHealthResponse, error) {
	out := new(SetHealthResponse)
	err := c.cc.Invoke(ctx, "/com.wdullaer.whoami.v1.WhoamiService/SetHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WhoamiServiceServer is the server API for WhoamiService service.
type WhoamiServiceServer interface {
	GetData(context.Context, *GetDataRequest) (*GetDataResponse, error)
	Bench(context.Context, *BenchRequest) (*BenchResponse, error)
	GetWhoami(context.Context, *GetWhoamiRequest) (*GetWhoamiResponse, error)
	GetHealth(context.Context, *GetHealthRequest) (*GetHealthResponse, error)
	SetHealth(context.Context, *SetHealthRequest) (*SetHealthResponse, error)
}

// UnimplementedWhoamiServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWhoamiServiceServer struct {
}

func (*UnimplementedWhoamiServiceServer) GetData(ctx context.Context, req *GetDataRequest) (*GetDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetData not implemented")
}
func (*UnimplementedWhoamiServiceServer) Bench(ctx context.Context, req *BenchRequest) (*BenchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bench not implemented")
}
func (*UnimplementedWhoamiServiceServer) GetWhoami(ctx context.Context, req *GetWhoamiRequest) (*GetWhoamiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWhoami not implemented")
}
func (*UnimplementedWhoamiServiceServer) GetHealth(ctx context.Context, req *GetHealthRequest) (*GetHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHealth not implemented")
}
func (*UnimplementedWhoamiServiceServer) SetHealth(ctx context.Context, req *SetHealthRequest) (*SetHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetHealth not implemented")
}

func RegisterWhoamiServiceServer(s *grpc.Server, srv WhoamiServiceServer) {
	s.RegisterService(&_WhoamiService_serviceDesc, srv)
}

func _WhoamiService_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhoamiServiceServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.wdullaer.whoami.v1.WhoamiService/GetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhoamiServiceServer).GetData(ctx, req.(*GetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhoamiService_Bench_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BenchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhoamiServiceServer).Bench(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.wdullaer.whoami.v1.WhoamiService/Bench",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhoamiServiceServer).Bench(ctx, req.(*BenchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhoamiService_GetWhoami_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWhoamiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhoamiServiceServer).GetWhoami(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.wdullaer.whoami.v1.WhoamiService/GetWhoami",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhoamiServiceServer).GetWhoami(ctx, req.(*GetWhoamiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhoamiService_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhoamiServiceServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.wdullaer.whoami.v1.WhoamiService/GetHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhoamiServiceServer).GetHealth(ctx, req.(*GetHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhoamiService_SetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhoamiServiceServer).SetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.wdullaer.whoami.v1.WhoamiService/SetHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhoamiServiceServer).SetHealth(ctx, req.(*SetHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WhoamiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.wdullaer.whoami.v1.WhoamiService",
	HandlerType: (*WhoamiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetData",
			Handler:    _WhoamiService_GetData_Handler,
		},
		{
			MethodName: "Bench",
			Handler:    _WhoamiService_Bench_Handler,
		},
		{
			MethodName: "GetWhoami",
			Handler:    _WhoamiService_GetWhoami_Handler,
		},
		{
			MethodName: "GetHealth",
			Handler:    _WhoamiService_GetHealth_Handler,
		},
		{
			MethodName: "SetHealth",
			Handler:    _WhoamiService_SetHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "whoami.proto",
}
